// Treasure Island's fits on the real, meshopt-decoded GLBs (through core modelParts, what <Model> /
// <InstancedModel> draw): every model is in the manifest and drawn at the README's size; the palm's
// trunk base and the umbrella's pole sit on their rules footprints; the canopy clears the hatted
// explorer; the coin lies flat at its centre.
import { describe, expect, it } from "vitest";
import { Box3, BufferGeometry, Float32BufferAttribute, Group, Matrix4, Mesh, Vector3 } from "three";
import { modelParts } from "@/arcade3d/core/assets";
import { hasModel } from "@/arcade3d/core/modelManifest";
import { readCharacterGlb } from "@/arcade3d/core/rig/robotGlb";
import type { ModelAsset } from "@/arcade3d/core/types";
import { ASSETS, COIN_SIZE, CRAB_WIDTH, CRATE_SIZE, GULL_LENGTH, PALM_SIZE, UMBRELLA_HEIGHT, palmBaseOffset } from "./assets";
import { HAT } from "./Primitives";
import { PITCH } from "./looks";
import { PALM_TRUNK, SIGHT, UMBRELLA_CIRCLE } from "./rules";

/** The GLB's vertices as the asset's fit draws them (metres, model origin), optionally placed by `spot`. */
async function drawn(asset: ModelAsset, spot = new Matrix4()): Promise<Vector3[]> {
   const { local, node } = await readCharacterGlb(asset.url);
   const geometry = new BufferGeometry();
   geometry.setAttribute("position", new Float32BufferAttribute(local, 3));
   const mesh = new Mesh(geometry);
   mesh.position.fromArray(node);
   const root = new Group();
   root.add(mesh);
   const parts = modelParts(root, asset);
   expect(parts).toHaveLength(1);
   const m = spot.clone().multiply(parts[0].matrix);
   const points: Vector3[] = [];
   for (let i = 0; i < local.length; i += 3) points.push(new Vector3(local[i], local[i + 1], local[i + 2]).applyMatrix4(m));
   geometry.dispose();
   return points;
}
const sizeOf = (points: Vector3[]) => new Box3().setFromPoints(points).getSize(new Vector3());

describe("treasure-island models", () => {
   it("are all in the manifest (none of them is generated by this game but the crab)", () => {
      for (const asset of Object.values(ASSETS)) expect(hasModel(asset.url), asset.url).toBe(true);
      expect(ASSETS.crab.url).toBe("/models/3d/treasure-island/crab.glb");
   });

   it("are drawn at the README's sizes", async () => {
      const palm = sizeOf(await drawn(ASSETS.palm));
      expect(palm.y).toBeCloseTo(PALM_SIZE.height, 2);
      expect(palm.x).toBeCloseTo(PALM_SIZE.crown, 2);
      expect(palm.z).toBeCloseTo(PALM_SIZE.crown, 2);
      expect(sizeOf(await drawn(ASSETS.umbrella)).y).toBeCloseTo(UMBRELLA_HEIGHT, 2);
      expect(sizeOf(await drawn(ASSETS.crate)).x).toBeCloseTo(CRATE_SIZE, 2);
      const chest = sizeOf(await drawn(ASSETS.chest));
      expect([chest.x, chest.y, chest.z].map((v) => +v.toFixed(2))).toEqual([0.9, 0.6, 0.6]);
      expect(sizeOf(await drawn(ASSETS.rock)).x).toBeCloseTo(1, 2);
      expect(sizeOf(await drawn(ASSETS.gull)).z).toBeCloseTo(GULL_LENGTH, 2);
      expect(sizeOf(await drawn(ASSETS.crab)).x).toBeCloseTo(CRAB_WIDTH, 2);
      const coin = await drawn(ASSETS.coin);
      const box = new Box3().setFromPoints(coin);
      expect(box.getSize(new Vector3()).x).toBeCloseTo(COIN_SIZE, 2);
      // centred on its origin (the pile places coins by their centre)
      expect(Math.abs(box.getCenter(new Vector3()).y)).toBeLessThan(0.01);
   });

   it("puts each palm's trunk base on its footprint (r 0.3) at any turn and size", async () => {
      for (const [yaw, size] of [[0, 1], [1.3, 0.9], [3.6, 1.15], [5.2, 1]]) {
         const o = palmBaseOffset(yaw, size);
         const spot = new Matrix4().makeRotationY(yaw).scale(new Vector3(size, size, size)).setPosition(-o.x, 0, -o.z);
         const base = (await drawn(ASSETS.palm, spot)).filter((p) => p.y < 0.12 * size);
         const c = new Box3().setFromPoints(base).getCenter(new Vector3());
         expect(Math.hypot(c.x, c.z), `yaw ${yaw}`).toBeLessThan(0.06);
         // the trunk at the ground fills about the footprint, never far outside it
         const far = Math.max(...base.map((p) => Math.hypot(p.x, p.z)));
         expect(far).toBeLessThan(PALM_TRUNK * size + 0.12);
      }
   });

   it("stands the umbrella's pole inside its footprint, and its canopy's lowest edge above the hatted explorer", async () => {
      const points = await drawn(ASSETS.umbrella);
      const pole = points.filter((p) => p.y < 1);
      expect(Math.max(...pole.map((p) => Math.hypot(p.x, p.z)))).toBeLessThan(UMBRELLA_CIRCLE.r);
      // the canopy: everything more than 0.6 m from the pole (where the explorer's head can be)
      const canopyLow = Math.min(...points.filter((p) => Math.hypot(p.x, p.z) > 0.6).map((p) => p.y));
      expect(canopyLow).toBeGreaterThan(1.556 + HAT.top + 0.05);
   });

   it("matches the rules' sight strips (rules SIGHT) to the drawn crown and canopy at the camera's pitch", async () => {
      const t = Math.tan(PITCH);
      const palm = (await drawn(ASSETS.palm)).filter((p) => Math.hypot(p.x, p.z) > 0.6);
      const crownLow = Math.min(...palm.map((p) => p.y));
      expect(SIGHT.palm.near).toBeLessThanOrEqual(crownLow / t);
      expect(SIGHT.palm.far).toBeGreaterThanOrEqual(PALM_SIZE.height / t);
      expect(SIGHT.palm.r).toBeCloseTo(PALM_SIZE.crown / 2, 2);
      const canopy = (await drawn(ASSETS.umbrella)).filter((p) => Math.hypot(p.x, p.z) > 0.6);
      expect(SIGHT.umbrella.near).toBeLessThanOrEqual(Math.min(...canopy.map((p) => p.y)) / t + 0.01);
      expect(SIGHT.umbrella.far).toBeGreaterThanOrEqual(UMBRELLA_HEIGHT / t - 0.01);
      expect(SIGHT.umbrella.r).toBeGreaterThanOrEqual(Math.max(...canopy.map((p) => Math.hypot(p.x, p.z))) - 0.01);
   });
});
